### ISSUE TITLE
Flush to output to file

### ISSUE THREAD

**Issue by telemmaite** [icza/bitio#2]
How can I call Flush so that my file gets written?
```go
func WriteToFile() {
	// open output file
	fo, err := os.Create("output.txt")
	if err != nil {
		panic(err)
	}
	// close fo on exit and check for its returned error
	defer func() {
		if err := fo.Close(); err != nil {
			panic(err)
		}
	}()
	// make a write buffer
	w := bitio.NewWriter(fo)
	err = w.WriteBits(0x08, 8)
	if err != nil {
		panic(err)
	}
//????
	//w.Flush()
	err = w.Close()
	if err != nil {
		panic(err)
	}
}
```

**Comment by icza** [comment]
There is no `Flush()` method as that would require writing an optionally incomplete byte.

If you do need this functionality, you may call `Writer.Align()` which is basically a `Flush()` operation. It will result in any cached bits to be written out, and the next bits will start in a new byte. When reading the stream, the client will also have to call `Reader.Align()` in union with the `Writer.Align()` call.

**Comment by telemmaite** [comment]
When I write exactly 8 bits 1 byte, Align goes directly to https://github.com/icza/bitio/blob/master/writer.go#L170.

About 

> Also note that Writer.Flush() only flushes the cache of the bitio.Writer, it does not flush its underlying io.Writer, that you have to do manually.

Any suggestion how to that , when these `out` is private?

**Comment by icza** [comment]
Yes, if the internal cache is empty, by definition `Writer.Align()` does not have to do anything, because every bits written to it is already written to the underlying `io.Writer`.

And yes, the underlying `io.Writer` is not exposed, but you should have it already, because you have to pass it when creating `bitio.Writer` via `bufio.NewWriter()`. So you can store the underlying `io.Writer`, and when you want to perform a "flush", you may do it like:

    var w io.Writer = ... // Your io.Writer

    bw := bufio.NewWriter(w) // Create bufio.Writer
    // Use bw, write bits into it

    // And when you want to flush:
    skipped, err := bw.Align()
    // Handle err
    // Flush underlying writer if it has a Flush() method:
    if f, ok := w.(interface {
        Flush()
    }); ok {
        f.Flush()
    }

That last flushing can be written simpler if you have a `Flusher` interface definition:

    type Flusher interface {
        Flush()
    }

And then:

    if f, ok := w.(Flusher); ok {
        f.Flush()
    }

Or if you're using a file, then:

    f, err := os.Open("data.dat")
    if err != nil {
        // Handle err
        return
    }
    defer f.Close()

    bw := bufio.NewWriter(f) // Create bufio.Writer
    // Use bw, write bits into it

    // And when you want to flush:
    skipped, err := bw.Align()
    // Handle err
    err = f.Sync()
    // Handle err

**Comment by telemmaite** [comment]
Thanks a lot for your detailed answer! I will try that it makes sense.
I will update here once I get it working saving to a file.

**Comment by telemmaite** [comment]
I tried this and is not working the file is empty in the end. Not sure why. Please note in all your examples you have bufio vs bitio in mine, I guess it was typo?
```go
func WriteToFile() {
	// open output file
	fo, err := os.Create("output.txt")
	if err != nil {
		panic(err)
	}
	// close fo on exit and check for its returned error
	defer func() {
		if err := fo.Close(); err != nil {
			panic(err)
		}
	}()
	// make a write buffer

	w := bitio.NewWriter(fo)

	err = w.WriteBits(0x08, 8)
	err = w.WriteBits(0x08, 8)
	err = w.WriteBits(0x08, 8)
	err = w.WriteBits(0x08, 8)

	skipped, err := w.Align()
	fmt.Println("skipped", skipped)
	if err != nil {
		panic(err)
	}

	err = fo.Sync()

	if err != nil {
		panic(err)
	}
	err = w.Close()
	if err != nil {
		panic(err)
	}
}
```

This is the only way I got it working.
```go
func WriteToFile() {
	// open output file
	fo, err := os.Create("output.txt")
	if err != nil {
		panic(err)
	}
	// close fo on exit and check for its returned error
	defer func() {
		if err := fo.Close(); err != nil {
			panic(err)
		}
	}()
	// make a write buffer
	wr := bufio.NewWriter(fo)
	w := bitio.NewWriter(wr)

	err = w.WriteBits(0x08, 8)
	err = w.WriteBits(0x08, 8)
	err = w.WriteBits(0x08, 8)
	err = w.WriteBits(0x08, 8)

	if err != nil {
		panic(err)
	}
	wr.Flush()
	//x, ok := &fo.(io.Writer)
	err = w.Close()
	if err != nil {
		panic(err)
	}
}
```

I am quite new with `go` and unsure why the `fo.Sync()` is not working.

**Comment by icza** [comment]
You are right, all references to `bufio.Writer` in my previous answer were typo, and they should've been `bitio.Writer`. Edited - fixed.

You are also right, there was an error in the implementation which did not flush the internal `bufio.Writer` if one was used. Fixed this, and your examples now work.

Moreover note that the `Writer.Align()` call in your example is not even required, as you write multiple of 8 bits, so that is always a full byte, but in the general case, `Aligh()` might be needed if you intend to write further data. Calling `Writer.Close()` will write everything to the underlying writer regardless if you called `Aligh()` prior or not.

The following simplified example now works as expected:

	// open output file
	fo, err := os.Create("output.txt")
	if err != nil {
		panic(err)
	}
	// close fo on exit and check for its returned error
	defer func() {
		if err := fo.Close(); err != nil {
			panic(err)
		}
	}()

	w := bitio.NewWriter(fo)

	err = w.WriteBits(0x08, 8)
	err = w.WriteBits(0x08, 8)
	err = w.WriteBits(0x08, 8)
	err = w.WriteBits(0x08, 8)

	// No need to call w.Align() in this special case, but it is required in general
	// (if you remove this, it will still work)
	skipped, err := w.Align()
	fmt.Println("skipped", skipped)
	if err != nil {
		panic(err)
	}

	// No need to call fo.Sync() if you close the file,
	// that is only needed if you intend to write more.

	err = w.Close()
	if err != nil {
		panic(err)
	}

**Comment by icza** [comment]
Closing as resolved.
